### ISSUE TITLE
How to register OpenSessionInViewFilter?

### ISSUE THREAD

**Issue by Ramblurr** [code8/tapestry-boot#1]
This little library has been working great for me, however when using spring data jpa, I'm trying to register a OpenSessionInViewFilter, but can't get it quite working. The filter is registered and the bean instantiated, but I'm still getting LazyInitializationExceptions.

The old web.xml config I'm trying to port is:

``` xml
    <filter>
        <filter-name>OpenSessionFilter</filter-name>
        <filter-class>
            org.springframework.orm.hibernate4.support.OpenSessionInViewFilter</filter-class>
    </filter>

    <filter-mapping>
        <filter-name>OpenSessionFilter</filter-name>
        <url-pattern>/*</url-pattern>
    </filter-mapping>

    <filter>
        <filter-name>app</filter-name>
        <filter-class>org.apache.tapestry5.spring.TapestrySpringFilter</filter-class>
    </filter>
```

And my boot config:

``` java
@SpringBootApplication
public class Launcher {
    public static void main(String[] args) {
        new SpringApplicationBuilder(Launcher.class)
                .web(true)
                .run(args);
    }

    @Bean
    public FilterRegistrationBean registerOpenSessionInViewFilterBean() {
        FilterRegistrationBean registrationBean = new FilterRegistrationBean();
        OpenSessionInViewFilter filter = new OpenSessionInViewFilter();
        registrationBean.setFilter(filter);
        registrationBean.setOrder(5); // I've played with the order
        return registrationBean;
    }
```

Do I need to dive into tapestry-boot to fix this?

**edit:** the application I'm migrating used tapestry-spring and TapestrySpringFilter, but now it isn't obviously. 

I edited the TapestryFilter provided by tapestry-boot, adding `setOrder(10)` in the constructor.

This resulted in the filter being loaded correctly but the `LazyInitializationException` persists. You can see in the stacktrace below that OpenSessionInViewFilter was invoked.

```
org.apache.tapestry5.ioc.internal.OperationException: Render queue error in Expansion[PropBinding[expansion mypage/Edit(model.othermodel.name)]]: could not initialize proxy - no Session
    at org.apache.tapestry5.ioc.internal.OperationTrackerImpl.logAndRethrow(OperationTrackerImpl.java:186) ~[tapestry-ioc-5.4.1.jar:na]
    at org.apache.tapestry5.ioc.internal.OperationTrackerImpl.run(OperationTrackerImpl.java:62) ~[tapestry-ioc-5.4.1.jar:na]
    at org.apache.tapestry5.ioc.internal.PerThreadOperationTracker.run(PerThreadOperationTracker.java:60) ~[tapestry-ioc-5.4.1.jar:na]
    at org.apache.tapestry5.ioc.internal.RegistryImpl.run(RegistryImpl.java:1254) ~[tapestry-ioc-5.4.1.jar:na]
    at org.apache.tapestry5.internal.services.RequestOperationTracker.handlePageRender(RequestOperationTracker.java:66) ~[tapestry-core-5.4.1.jar:na]
    at $ComponentRequestHandler_94ac265764f4.handlePageRendewn Source) ~[na:na]
    at $ComponentRequestHandler_94ac2657642d.handlePageRender(Unknown Source) ~[na:na]
    at org.apache.tapestry5.internal.services.PageRenderDispatcher.dispatch(PageRenderDispatcher.java:55) ~[tapestry-core-5.4.1.jar:na]
    at $Dispatcher_94ac265764c8.dispatch(Unknown Source) ~[na:na]
    at $Dispatcher_94ac26576473.dispatch(Unknown Source) ~[na:na]
    at org.apache.tapestry5.modules.TapestryModule$RequestHandlerTerminator.service(TapestryModule.java:305) ~[tapestry-core-5.4.1.jar:na]
    at org.apache.tapestry5.internal.services.RequestErrorFilter.service(RequestErrorFilter.java:26) ~[tapestry-core-5.4.1.jar:na]
    at $RequestHandler_94ac265764c7.service(Unknown Source) [na:na]
    at org.apache.tapestry5.modules.TapestryModule$3.service(TapestryModule.java:846) [tapestry-core-5.4.1.jar:na]
    at $RequestHandler_94ac265764c7.service(Unknown Source) [na:na]
    at org.apache.tapestry5.modules.TapestryModule$2.service(TapestryModule.java:836) [tapestry-core-5.4.1.jar:na]
    at $RequestHandler_94ac265764c7.service(Unknown Source) [na:na]
    at org.apache.tapestry5.internal.services.StaticFilesFilter.service(StaticFilesFilter.java:89) [tapestry-core-5.4.1.jar:na]
    at $RequestHandler_94ac265764c7.service(Unknown Source) [na:na]
    at org.apache.tapestry5.internal.services.CheckForUpdatesFilter$2.invoke(CheckForUpdatesFilter.java:105) [tapestry-core-5.4.1.jar:na]
    at org.apache.tapestry5.internal.services.CheckForUpdatesFilter$2.invoke(CheckForUpdatesFilter.java:95) [tapestry-core-5.4.1.jar:na]
    at org.apache.tapestry5.ioc.internal.util.ConcurrentBarrier.withRead(ConcurrentBarrier.java:83) [tapestry-ioc-5.4.1.jar:na]
    at org.apache.tapestry5.internal.services.CheckForUpdatesFilter.service(CheckForUpdatesFilter.java:119) [tapestry-core-5.4.1.jar:na]
    at $RequestHandler_94ac265764c7.service(Unknown Source) [na:na]
    at $RequestHandler_94ac2657649d.service(Unknown Source) [na:na]
    at org.apache.tapestry5.modules.TapestryModule$HttpServletRequestHandlerTerminator.service(TapestryModule.java:256) [tapestry-core-5.4.1.jar:na]
    apache.tapestry5.upload.internal.services.MultipartServletRequestFilter.service(MultipartServletRequestFilter.java:45) [tapestry-upload-5.4.1.jar:na]
    at $HttpServletRequestHandler_94ac265764c4.service(Unknown Source) [na:na]
    at org.apache.tapestry5.internal.gzip.GZipFilter.service(GZipFilter.java:59) [tapestry-core-5.4.1.jar:na]
    at $HttpServletRequestHandler_94ac265764c4.service(Unknown Source) [na:na]
    at org.apache.tapestry5.internal.services.IgnoredPathsFilter.service(IgnoredPathsFilter.java:62) [tapestry-core-5.4.1.jar:na]
    at $HttpServletRequestFilter_94ac2657645a.service(Unknown Source) [na:na]
    at $HttpServletRequestHandler_94ac265764c4.service(Unknown Source) [na:na]
    at org.apache.tapestry5.modules.TapestryModule$1.service(TapestryModule.java:796) [tapestry-core-5.4.1.jar:na]
    at $HttpServletRequestHandler_94ac265764c4.service(Unknown Source) [na:na]
    at $HttpServletRequestHandler_94ac26576458.service(Unknown Source) [na:na]
    at info.code8.tapestry.TapestryFilter.doFilter(TapestryFilter.java:49) [tapestry-boot-0.1.0-SNAPSHOT.jar:na]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.springframework.orm.hibernate5.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:151) [spring-orm-4.2.5.RELEASE.jar:4.2.5.RELEASE]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.2.5.RELEASE.jar:4.2.5.RELEASE]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
```

**Comment by Ramblurr** [comment]
FYI, I got this fixed by using `OpenEntityManagerInViewFilter` instead of `OpenSessionInViewFilter`. 

``` java
// inside my @SpringBootApplication annotated class

    @Bean
    public HibernateJpaSessionFactoryBean sessionFactory() {
        return new HibernateJpaSessionFactoryBean();
    }

    @Bean
    public FilterRegistrationBean registerOpenSessionInViewFilter() {
        FilterRegistrationBean registrationBean = new FilterRegistrationBean();
        OpenEntityManagerInViewFilter filter = new OpenEntityManagerInViewFilter();
        registrationBean.setFilter(filter);
        registrationBean.setOrder(5);
        return registrationBean;
    }
```
